name: Berkeley Schema Change
description: Describe all PRs for changes during berkeley-schema freeze
title: "[berkeley-schema] <title>"
body:
  - type: markdown
    attributes:
      value: |
        # Guidelines
        
        ## _Soft_ Schema Freeze
        The nmdc-schema and berkeley-schema are under a light freeze this means changes **should not** be made that have any down stream implications. 
        To ensure this, PRs need to be closely reviewed with **every** component of the NMDC in mind.
        
        ## Reviewers
        To ensure no changes are made unexpectedly, ALL berkeley-schema refacror roll out task coordinators should be listed as reviewrs for ALL PRs. 
        See [squad proposal](https://docs.google.com/document/d/1XXN1YuaBuSkxPXeiLKm5YxYzXTamBPQrzzeLhlh7PWs/edit#heading=h.u52g8v319adh) for list of names. Task coordinators should review PRs and provide feedback within a week. Expedition, questions, and discussion can happen at any meeting.
        PRs should NOT be merged until they have been approved by all task coordinators.
  - type: checkboxes
    attributes: 
      label: What type of PR is this?
      description: Select all applicable options to catagorize this PR. 
      options:
        - label: Refactor
        - label: Feature
        - label: Bug Fix
        - label: Optimization
        - label: Documentation Update
        - label: Content change (Ex- slot or Class name, slot multivalued changes, slot movement from one Class to another, creating a new slot/Class, Enum value changes)
        - label: Informitive change (Ex- descriptions of slots, classes, or enums, removal of unused, commented, or invalid code, updated mappings of terms, classes, or slots to ontologies, added an additional Enum to accommodate new or future metadata)
        - label: changes to ANY files in /src/schema
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: PRs should be small and concise
      value: "Provide a description of the PR."
    validations:
      required: true
  - type: input
    attributes:
      label: Issues
      description: What issues are part of this PR?
      placeholder: ex. /issues/issues/100, nmdc-schema/issues/400
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Added or Updated tests & example files?
      description: Yes or no, if you added or changed any test or example files
      options:
        - label: Yes
        - label: No
        - label: I need help with writing tests
    validations:
      required: false
  - type: textarea
    attributes:
      label: If no, why
      description: Provide why no examples or tests were updated or added
      value: "This is why I have no tests or example files."
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Will this change to the schema result in any invalid data?
      description: Yes or no, if you added or changed any test or example files
      options:
        - label: Yes
        - label: No
        - label: Unsure
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Will this change to the schema require a migration?
      description: Ideally, no additional migrations will be performed with the schema soft freeze
      options:
        - label: Yes
        - label: No
        - label: Unsure
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Migrations are required if the change results in any existing data being no longer valid. This includes
           -slot or Class name changes 
           -slot multiplicity changes (from a single value to a list or vice versa) 
           -slot movement from one Class to another 4) Enum value changes.     
  - type: textarea
    attributes:
      label: Downstream implications
      description: Ideally no schema changes will be performed that have down stream implications. If your change does results in downstream changes, provide a justification/need for this change
      value: "Examples of downstream changes include any change that requires an update or change to workflows, workflow automation, Postgres ingest, Jupyter notebooks, runtime, & more"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Are there any post deployment tasks we need to perform?
      description: Indicate any tasks that need completed after this PR is merged.
    validations:
      required: false
